services:
    devenv:
        build: .
        container_name: devenv
        volumes:
            - "./d/cert:/cert"
            - "./d/conf:/conf"
        ports:
            - "80:80"
            - "443:443"